# Generated by Django 5.0.6 on 2024-05-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_description_member_address_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='members',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='type',
            new_name='order_type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='address_data',
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('S', 'Science & Tech'), ('F', 'Fiction'), ('B', 'Biography'), ('T', 'Travel'), ('O', 'Other')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.CharField(default='USA', max_length=20),
        ),
    ]
