# Generated by Django 5.0.7 on 2024-07-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0003_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='events/event_image.jpg', upload_to='events/'),
        ),
    ]
