# Generated by Django 5.0.6 on 2024-07-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0005_category_customer_product_order_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='bio',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='role',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
