# Generated by Django 5.0.6 on 2024-07-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0006_rename_bio_volunteer_reason_remove_volunteer_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(default='', max_length=250),
        ),
    ]
