# Generated by Django 5.0.6 on 2024-07-23 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0010_contact_favorite_holder_remove_favorite_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='volunteer_images/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits long.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='reason',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
